/*var password = prompt("Enter your password");
var confirmpassword = prompt("confirm your password");

function validate(a, b){
	if( a == b){

		return "password validated";

	}

	 else {
			return "Password do not match";
		}
}
*/
// alert( alert(1) || 2 || alert(3) );

/*ans--1 and 2*/

// Create a function which takes two input and (a,b) and display the sum, sub, multiplication, devision of those two numbers.

/**/


/*var even = prompt("enter a number");

function check(a){
	if(a%2==0){
		console.log("even number");
	}
	else {
		console.log("odd number");
	}
}*/

/*
var table = prompt("enter a number");
// var a ;
alert(table);

for(var i=0; i<=10; i++){

	console.log(table*i);
}*/

// Output: var x = 10 + "1"; console.log(x); typeof x;

// var x = 10 + "1";
// console.log(x);
// typeof x; //string

// Funnctionn to calculate the Factorial of a Number
/*
  var x = prompt("enter a number");

   function fact(x){
	   	if(x < 0){
	   		return -1;
	   	}
	   	else if (x == 0){
	   		
	   		return 1;
	   	}	
	   	else {
	   		return (x * fact(x - 1));
	   	}
   }*/


   // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

var a = 0;
var b = 1;
var sum = 0;
var c;

   while(b < 4000000){
        c = b + a;
        a = b;
        b = c; 
        if(b % 2 === 0) {
            sum += b;
        console.log(sum); //4613732
        }
   }
 
 /*negative*/

/* var negativenum = prompt("Enter a number") ;

function neg(){
 if(negativenum < 0){
 	 console.log(negativenum);
 }  else {
 	console.log();
 }
 } */  
/*
 var pos = prompt("Enter a number") ;

function neg(){
 if(pos < 0){
 	 console.log(" ");
 }  else {
 	console.log(pos);
 }
 }*/

 // Funnction to take two input and show the relation using =, > or < i.e (21,45) 21 < 45, (23,12) 23 > 12

/*var a = prompt("enter a number");
var b = prompt("enter second number");

function checknumber(){
	if(a > b){
		console.log(a);
	} 
	else if(a == b){
		console.log(a + "is greater than" + b);
	}
		else if (b > a) {
				console.log(b + "is greater than" + a);
		}
		else {
			console.log("not a number");
		}
}*/

// Funnction to Check Whether a Character is Vowel or Consonant

var c = prompt("Enter a character");

function character(){
	if(c=="a" || c=="i" ||c=="e" || c=="o" || c=="u"){
	console.log("character is vowel");
}
	else if ( c=="A" || c=="I" ||c=="E" || c=="O" || c=="U"){
		console.log("character is vowel");
	}
	else {
		console.log("character is Consonant");
	}
}

// Funnction to Find the Largest Number Among Three Numbers

var a = 8;
var b = 10;
var c = 15;

if(a > b && a > c){
	console.log(a + "is Largest Numbers");
}
else if(b > a && b > c){
	console.log(b + "is Largest Numbers");
}
else {
	console.log(c + "is Largest Numbers");
}


// Find the sum of all the multiples of 3 or 5 below 1000.

/*var sum=0;

 for(var i=0; i<1000; i++){
 	if(i%5==0 || i%3==0){
 		sum = sum +i;
 	}	
 }
 console.log(sum);*/ //233168

// Take two numbers and what to do with that number from user.
// Define an object with these function (add, sub, multiply, divide). Perform the operation

var operation = {
	add: function(a, b){
		return a+b;
	},
	sub: function(a, b){
		return a - b;
	},
	multiply: function(a, b){
		return a * b;
	},

	div: function(a, b){
		return a / b;
	},
}


/*mod */
 
 var mod = (225%6);
 console.log(mod);

